version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "[%(asctime)s] [%(name)s - %(levelname)s] : %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  detailed:
    format: "[%(asctime)s] [%(name)s - %(levelname)s] [%(filename)s:%(lineno)d] %(funcName)s(): %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  console_formatter:
    (): wowberg.logger.ConsoleFormatter
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console_formatter
    stream: ext://sys.stdout
  
  auction_file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: "./logs/auction.log"
    mode: "a"
  
  blizzard_file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: "./logs/blizzard.log"
    mode: "a"

  sql_file:
    class: logging.FileHandler
    level: INFO
    formatter: detailed
    filename: "./logs/sqlalchemy.log"
    mode: "a"

loggers:
  wowberg:
    level: INFO
    handlers:
      - console
    propagate: false
  
  wowberg.auction:
    level: DEBUG
    handlers:
      - console
      - auction_file
    propagate: false
  
  wowberg.blizzard:
    level: DEBUG
    handlers:
      - console
      - blizzard_file
    propagate: false

  sqlalchemy.engine:
    level: INFO
    handlers:
      - sql_file
    propagate: false

root:
  level: WARNING
  handlers:
    - console
